# Generated by Django 5.0.6 on 2024-07-05 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='featured',
            name='artist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.artist'),
            preserve_default=False,
        ),
    ]
