# Generated by Django 5.0.6 on 2024-07-05 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_images_artist_images_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='is_copyright',
            field=models.BooleanField(default=False),
        ),
    ]
