# Generated by Django 5.0.6 on 2024-07-05 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_images_is_copyright'),
    ]

    operations = [
        migrations.CreateModel(
            name='Copyright',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.CharField(max_length=4)),
                ('year', models.CharField(max_length=4)),
                ('co_authors', models.CharField(max_length=30)),
                ('work_type', models.CharField(max_length=10)),
                ('other', models.CharField(blank=True, max_length=10, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_processed', models.BooleanField(default=False)),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.images')),
            ],
        ),
    ]
