# Generated by Django 5.0.6 on 2024-07-06 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='itmes',
            new_name='items',
        ),
    ]
