# Generated by Django 5.0.6 on 2024-07-07 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_transaction_is_paid_transaction_is_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='has_new_message',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buyer',
            name='has_new_message',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('from_artist', models.BooleanField()),
                ('body', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.artist')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.buyer')),
            ],
        ),
    ]
