# Generated by Django 5.0.6 on 2024-07-07 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_chat_chat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='body',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='date',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='from_artist',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='image',
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('from_artist', models.BooleanField()),
                ('body', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.chat')),
            ],
        ),
    ]
