# Generated by Django 5.0.6 on 2024-07-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_chat_piece'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='pfp',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='buyer',
            name='pfp',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
