# Generated by Django 5.0.6 on 2024-07-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_artist_pfp_alter_buyer_pfp'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_read',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
