# Generated by Django 5.0.6 on 2024-07-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_remove_chat_is_read_artist_is_read_buyer_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_read',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
