# Generated by Django 5.0.6 on 2024-07-08 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_support_ticket_support_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='date_of_creation',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 7, 8, 14, 55, 46, 367061, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
