# Generated by Django 5.0.6 on 2024-07-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_chat_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Swap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swap_id', models.CharField(max_length=20)),
                ('buyer', models.CharField(max_length=30)),
                ('artist', models.CharField(max_length=30)),
                ('piece', models.CharField(max_length=30)),
                ('piece_description', models.TextField()),
                ('price', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='available_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artist',
            name='uncleared_balance',
            field=models.IntegerField(default=0),
        ),
    ]
