# Generated by Django 5.0.6 on 2024-07-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_chat_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='err',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
