# Generated by Django 5.0.6 on 2024-07-08 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_alter_chat_err'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='artist_err',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
