# Generated by Django 5.0.6 on 2024-07-08 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_chat_artist_err'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='swaps_completed',
            field=models.IntegerField(default=0),
        ),
    ]
