# Generated by Django 5.0.6 on 2024-07-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_artist_swaps_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='image_id',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
