# Generated by Django 5.0.6 on 2024-07-14 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_images_image_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='images/steps')),
                ('header', models.CharField(max_length=50)),
                ('step', models.TextField()),
                ('note', models.TextField()),
            ],
        ),
    ]
