# Generated by Django 5.0.6 on 2024-07-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='info',
            field=models.CharField(default='copyright', max_length=10),
            preserve_default=False,
        ),
    ]
